###Create a new Report

POST  http://localhost:3000/reports
Content-Type: application/json


{
  "make": "Toyota",

  "model": "Toyota",

  "year": 2022,

  "mileage": 27000,

  "lng": 0,

  "lat": 0,

  "price": 875000

}

### Approving a report
PATCH http://localhost:3000/reports/7
Content-Type: application/json


{
  "approved": true
}


### get estimate report
GET http://localhost:3000/reports?make=Toyota&model=Toyota&year=2022&mileage=27000&lng=0&lat=0